[build]
builder = "NIXPACKS"
nixpacksVersion = "1.24.1"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_22", "npm"]

[deploy]
startCommand = "npm run start:production"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
