[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_23"]

[deploy]
startCommand = "npm run start:production"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
